ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- [관리자 계정] member 계정 생성
    CREATE USER osh_member IDENTIFIED BY member1234;
    
    -- [관리자 계정] CONNECT, RESOURE + CREATE VIEW 권한 부여 + 객체 생성 공간 할당
    GRANT CONNECT, RESOURCE, CREATE VIEW TO osh_member;
    ALTER USER osh_member DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
    
    -- osh_member 계정 접속 방법 추가
    
    --[멤버 계정]
    CREATE TABLE MEMBER (
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR(20) NOT NULL,
    MEMBER_PW VARCHAR(20) NOT NULL,
    MEMBER_NM VARCHAR(30) NOT NULL,
    MEMBER_GENDER CHAR(1) CHECK(MEMBER_GENDER IN ('M', 'F')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    SECESSION_FL CHAR(1) DEFAULT 'N' CHECK (SECESSION_FL IN ('Y', 'N'))
    
    );
    COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호(PK)';
    COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';
    COMMENT ON COLUMN MEMBER.MEMBER_PW IS '회원 비밀번호';
    COMMENT ON COLUMN MEMBER.MEMBER_NM IS '회원 이름';
    COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '회원 성별(M/F)';
    COMMENT ON COLUMN MEMBER. ENROLL_DATE IS '회원 가입일';
     COMMENT ON COLUMN MEMBER. SECESSION_FL IS '탈퇴여부(Y/N)';
     
     CREATE TABLE BOARD(
     BOARD_NO NUMBER PRIMARY KEY,
     BOARD_TITLE VARCHAR(200) NOT NULL,
      BOARD_CONTENT VARCHAR(4000) NOT NULL,
      CREATE_DATE DATE DEFAULT SYSDATE,
      READ_COUNT NUMBER DEFAULT 0,
      MEMBER_NO NUMBER REFERENCES MEMBER -- MEMBER 테이블 PK 참조
      
      
     );
      COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
      COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
      COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
      COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글 작성일';
      COMMENT ON COLUMN BOARD.CREATE_DATE IS '조회수';
      COMMENT ON COLUMN BOARD.READ_COUNT IS '회원 번호 (작성자)';
    
    CREATE TABLE REPLY (
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR(500) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MEMBER_NO NUMBER REFERENCES MEMBER, -- MEMBER 테이블 PK 참조
    BOARD_NO NUMBER REFERENCES BOARD ON DELETE CASCADE -- BOARD 테이블 PK 참조
    );
    
     COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호(PK)';
    COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글 내용';
     COMMENT ON COLUMN REPLY.CREATE_DATE IS '댓글 작성일';
     COMMENT ON COLUMN REPLY.MEMBER_NO IS '회원 번호(작성자)';
     COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글 번호(어떤 게시글의 댓글인지 확인)';
     
     -- 각 테이블 PK 생성용 시퀀스 생성
     CREATE SEQUENCE SEQ_MEMBER_NO; -- 1부터 1씩 증가, 반복 x
     CREATE SEQUENCE SEQ_BOARD_NO;
     CREATE SEQUENCE SEQ_REPLY_NO;
     
     DROP SEQUENCE SEQ_MEMBER_NO;
     DROP SEQUENCE SEQ_BOARD_NO;
     DROP SEQUENCE SEQ_REPLY_NO;
     
     --) 기본적으로 삭제 불가
     --> 삭제 옵션을 추가하면 가능
     --> ON DELETE SET NULL (자식 컬럼 NULL) ON DELETE CASCADE(참조하던 자식 행도 삭제)
     
     
     -- 제약조건은 ALTER (변경) 없음 -> 삭제 후 다시 추가
     
     -- 기존 REPLY 테이블에 FK 제약조건 삭제
     ALTER TABLE REPLY DROP CONSTRAINTS --제약조건명;
     
     -- 삭제 옵션이 추가된 FK를 다시 추가
     ALTER TABLE REPLY
     ADD FOREIGN KEY (BOARD_NO)
     REFERENCES BOARD
     ON DELETE CASCADE;
    -- 다시 1번 게시글 삭제 시도
    DELETE FROM BOARD WHERE BOARD_NO = 1;
     
ROLLBACK;

-- 게시글 수정
UPDATE BOARD SET BOARD_TITLE = ?,
BOARD_CONTENT = ?
WHERE BOARD_NO = ?;



-- 게시글 검색
SELECT BOARD_NO, BOARD_TITLE, CREATE_DATE, READ_COUNT, MEMBER_NM,
        (SELECT COUNT(*) FROM REPLY R
        WHERE R.BOARD_NO = B.BOARD_NO) REPLY_COUNT
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_TITLE LIKE '%' || '?' || '%'; -- 제목검색
-- WHERE BOARD_CONTENT LIKE '%' || ?' || '%'; -- 내용 검색

-- WHERE BOARD_TITLE LIKE '%' || '?' || '%' -- 제목 + 내용 
-- OR BOARD_CONTENT LIKE '%' || ?' || '%';

-- WHERE MEMBER_NM LIKE '%' || '?' || '%'; -- 작성자 검색

ORDER BY BOARD_NO DESC;


    
    
    